# Generated by Django 5.2.1 on 2025-05-20 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_latitude_service_longitude_serviceimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
