# Generated by Django 5.2.1 on 2025-06-05 15:41

import django.core.validators
import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(max_length=1000, validators=[django.core.validators.RegexValidator(message='Yalnız Azərbaycan hərfləri ilə yazılmalıdır.', regex='^[a-zA-ZəƏöÖüÜşŞçÇğĞıİ\\s.,!?-]+$'), utils.validators.not_only_whitespace, django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='review',
            name='username',
            field=models.CharField(default='Anonim hesab', max_length=20, validators=[django.core.validators.RegexValidator(message='Yalnız Azərbaycan hərfləri ilə yazılmalıdır.', regex='^[a-zA-ZəƏöÖüÜşŞçÇğĞıİ\\s.,!?-]+$')]),
        ),
    ]
