# Generated by Django 5.2.1 on 2025-06-06 13:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_review_comment_alter_review_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(max_length=1000, validators=[django.core.validators.RegexValidator(message='Yalnız Azərbaycan hərfləri ilə yazılmalıdır.', regex='^[a-zA-ZəƏöÖüÜşŞçÇğĞıİ\\s.,!?-]+$'), django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(1000)]),
        ),
    ]
