SELECT_CITY = [
    ("baku", "Bakı"),
    ("ganca", "Gəncə"),
    ("sumqayit", "Sumqayıt"),
    ("mingechevir", "Mingəçevir"),
    ("lenkeran", "Lənkəran"),
    ("shirvan", "Şirvan"),
    ("nakhchivan", "Naxçıvan"),
    ("sheki", "Şəki"),
    ("guba", "Quba"),
    ("gakh", "Qax"),
    ("qabala", "Qəbələ"),
    ("salyan", "Salyan"),
    ("masalli", "Masallı"),
    ("bilesuvar", "Biləsuvar"),
    ("imisli", "İmişli"),
    ("yevlakh", "Yevlax"),
    ("hajigabul", "Hacıqabul"),
    ("berde", "Bərdə"),
    ("aghdash", "Ağdaş"),
    ("sabirabad", "Sabirabad"),
    ("saatli", "Saatlı"),
    ("zardab", "Zərdab"),
    ("shamakhi", "Şamaxı"),
    ("aghsu", "Ağsu"),
    ("ismayilli", "İsmayıllı"),
    ("qusar", "Qusar"),
    ("khachmaz", "Xaçmaz"),
    ("shabran", "Şabran"),
    ("oguz", "Oğuz"),
    ("goychay", "Göyçay"),
    ("ucar", "Ucar"),
    ("zagatala", "Zaqatala"),
    ("balaken", "Balakən"),
    ("dashkasan", "Daşkəsən"),
    ("lachin", "Laçın"),
    ("kelbajar", "Kəlbəcər"),
    ("terter", "Tərtər"),
    ("fuzuli", "Füzuli"),
    ("jabrayil", "Cəbrayıl"),
    ("qubadli", "Qubadlı"),
    ("zangilan", "Zəngilan"),
    ("khodjavend", "Xocavənd"),
    ("aghdam", "Ağdam"),
    ("aghjabadi", "Ağcabədi"),
]

PROFESSİON_STATUS_LİST = [
    ('plumber', 'Santexnik'),
    ('washer_dishwasher_repair', 'Paltaryuyan/Qabyuyan ustası'),
    ('painter', 'Rəngsaz / Boya işləri'),
    ('refrigerator_repair', 'Soyuducu ustası'),
    ('carpenter', 'Dülgər'),
    ('air_conditioner_repair', 'Kondisioner ustası'),
    ('plasterer', 'Suvaqçı'),
    ('tv_repair', 'Televizor ustası'),
    ('tiler', 'Plitəçi / Kafel-plitə'),
    ('appliance_repair', 'Kiçik məişət əşyaları ustası'),
    ('decorator', 'Malyar'),
    ('boiler_repair', 'Kombi ustası'),
    ('phone_computer_repair', 'Telefon və kompüter ustası'),
    ('sewage_services', 'Kanalizasiya xidmətləri'),
    ('curtain_blinds_installation', 'Pərdə və jalüz quraşdırılması'),
    ('housekeeper', 'Ev xidmətçisi / Xadimə (Gündəlik və ya daimi)'),
    ('pet_care', 'Ev heyvanlarına qulluq (gəzdirilmə, baxım)'),
    ('physics_tutor', 'Fizika fənni'),
    ('chemistry_tutor', 'Kimya fənni'),
    ('azerbaijani_language_literature', 'Azərbaycan dili/ədəbiyyat fənni'),
    ('geography_tutor', 'Coğrafiya fənni'),
    ('history_tutor', 'Tarix fənni'),
    ('logic_tutor', 'Məntiq'),
    ('informatics_tutor', 'İnformatika fənni'),
    ('english_tutor', 'İngilis-dili fənni'),
    ('russian_tutor', 'Rus-dili fənni'),
    ('german_tutor', 'Alman-dili'),
    ('french_tutor', 'Fransız-dili'),
    ('early_childhood_education', 'Erkən inkişaf və məktəbəqədər hazırlıq'),
    ('makeup_artist', 'Vizajist / Makyaj ustası'),
    ('skincare_specialist', 'Dəri baxımı / Kosmetoloq'),
    ('manicurist_pedicurist', 'Manikür / Pedikür'),
    ('massage_therapist', 'Masajist'),
    ('physiotherapist', 'Fizioterapevt / Reabilitasiya'),
    ('speech_therapist', 'Loqoped'),
    ('child_development_specialist', 'Uşaq inkişafı üzrə mütəxəssis'),
    ('elderly_caregiver', 'Qocalara qulluq edən şəxs'),
    ('fitness_coach', 'Fitnes məşqçi'),
    ('nutritionist', 'Dietoloq / Qidalanma mütəxəssisi'),
    ('piano_teacher', 'Pianino müəllimi'),
    ('guitar_teacher', 'Gitara müəllimi'),
    ('vocal_teacher', 'Səs müəllimi'),
    ('dance_teacher', 'Rəqs müəllimi'),
    ('other', 'Digər')
]

EDUCATION_STATUS_LIST = [
    ('full_higher', 'Tam ali'),
    ('incomplete_higher', 'Natamam ali'),
    ('secondary', 'Orta'),
    ('vocational', 'Peşə təhsili'),
    ('secondary_specialized', 'Orta ixtisas təhsili'),
    ('none', 'Yoxdur')
]

GENDER_STATUS = [
        ('man', 'Kişi'),
        ('woman', 'Qadın')
    ]