# Generated by Django 5.2.1 on 2025-05-20 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.city')),
            ],
        ),
    ]
