# Generated by Django 5.2.1 on 2025-05-20 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='base_city',
        ),
        migrations.AddField(
            model_name='city',
            name='name',
            field=models.CharField(choices=[('baku', 'Bakı'), ('ganca', 'Gəncə'), ('sumqayit', 'Sumqayıt'), ('mingechevir', 'Mingəçevir'), ('lenkeran', 'Lənkəran'), ('shirvan', 'Şirvan'), ('nakhchivan', 'Naxçıvan'), ('sheki', 'Şəki'), ('guba', 'Quba'), ('gakh', 'Qax'), ('qabala', 'Qəbələ'), ('salyan', 'Salyan'), ('masalli', 'Masallı'), ('bilesuvar', 'Biləsuvar'), ('imisli', 'İmişli'), ('yevlakh', 'Yevlax'), ('hajigabul', 'Hacıqabul'), ('berde', 'Bərdə'), ('aghdash', 'Ağdaş'), ('sabirabad', 'Sabirabad'), ('saatli', 'Saatlı'), ('zardab', 'Zərdab'), ('shamakhi', 'Şamaxı'), ('aghsu', 'Ağsu'), ('ismayilli', 'İsmayıllı'), ('qusar', 'Qusar'), ('khachmaz', 'Xaçmaz'), ('shabran', 'Şabran'), ('oguz', 'Oğuz'), ('goychay', 'Göyçay'), ('ucar', 'Ucar'), ('zagatala', 'Zaqatala'), ('balaken', 'Balakən'), ('dashkasan', 'Daşkəsən'), ('lachin', 'Laçın'), ('kelbajar', 'Kəlbəcər'), ('terter', 'Tərtər'), ('fuzuli', 'Füzuli'), ('jabrayil', 'Cəbrayıl'), ('qubadli', 'Qubadlı'), ('zangilan', 'Zəngilan'), ('khodjavend', 'Xocavənd'), ('aghdam', 'Ağdam'), ('aghjabadi', 'Ağcabədi')], default='Bakı', max_length=50),
        ),
    ]
