# Generated by Django 5.2.1 on 2025-05-25 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_language_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='display_name',
            field=models.CharField(max_length=20),
        ),
    ]
