# Generated by Django 5.2.1 on 2025-05-25 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_language_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='display_name',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
