# Generated by Django 5.2.1 on 2025-05-24 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='master',
            name='email',
        ),
        migrations.RemoveField(
            model_name='master',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='master',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='master',
            name='username',
        ),
    ]
