# Generated by Django 5.2.1 on 2025-06-04 09:59

import django.core.validators
import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='note',
            field=models.CharField(max_length=1500, null=True, validators=[django.core.validators.RegexValidator(message='Yalnız Azərbaycan hərfləri ilə yazılmalıdır.', regex='^[a-zA-ZəƏöÖüÜşŞçÇğĞıİ\\s]+$'), utils.validators.not_only_whitespace, django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(1000)], verbose_name='Qeyd'),
        ),
        migrations.AlterField(
            model_name='master',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='masters/profile_pictures/'),
        ),
        migrations.AlterField(
            model_name='masterworkimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='masters/master_handwork_images/'),
        ),
    ]
