# Generated by Django 5.2.1 on 2025-05-24 20:23

import django.core.validators
import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_master_email_remove_master_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='experience',
            field=models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.RegexValidator(message='Yalnız Azərbaycan hərfləri ilə yazılmalıdır.', regex='^[a-zA-ZəƏöÖüÜşŞçÇğĞıİ\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='master',
            name='full_name',
            field=models.CharField(max_length=50, null=True, validators=[utils.validators.validate_full_name], verbose_name='Ad və soyad'),
        ),
    ]
