# Generated by Django 5.2.1 on 2025-06-06 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('services', '0001_initial'),
        ('users', '0002_alter_master_custom_profession_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='education',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='education_masters', to='core.education'),
        ),
        migrations.AlterField(
            model_name='master',
            name='profession_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='category_masters', to='services.category'),
        ),
        migrations.AlterField(
            model_name='master',
            name='profession_service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='profession_masters', to='services.service'),
        ),
    ]
