# Generated by Django 5.2.1 on 2025-05-22 15:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_master_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='phone_number',
            field=models.CharField(max_length=13, null=True, validators=[django.core.validators.RegexValidator(message='Mobil nömrə düzgün daxil edilməyib. 50 123 45 67 formatında daxil edin.', regex='^(50|51|55|70|77|99)[0-9]{7}$')], verbose_name='Mobil nömrə'),
        ),
    ]
