# Generated by Django 5.2.1 on 2025-06-07 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_master_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='is_master',
            field=models.BooleanField(default=False, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='master',
            name='user_role',
            field=models.CharField(choices=[('Master', 'Usta'), ('Customer', 'Müştəri'), (None, 'none')], default='None'),
        ),
    ]
