# Generated by Django 5.2.1 on 2025-06-07 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_master_is_master_master_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='user_role',
            field=models.CharField(choices=[('Master', 'Usta'), ('Customer', 'Müştəri')]),
        ),
    ]
