# Generated by Django 5.2.1 on 2025-06-07 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_master_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='slug',
            field=models.SlugField(blank=True, editable=False),
        ),
    ]
